### ISSUE TITLE
[BUG] Top 2 data refresh issue

### ISSUE THREAD

**Issue by nicplet-netizen** [Watchface-io/Watchfaces#638]
Note: Please add a label with the watchface you're expericing this issue on. If multiple, select "All watchfaces".

**Required:**
 - Watchface (Select as label): Fenix Like V3 - GB
 - Watch Model: Fenix 7 Sapphire Solar
 - Describe the bug:When the OWM location in Top 2 data section refresh with a shorter name than the previous one, the 2 locations are overlapping

**Optional:**
 - Watch firmware: 23.18
 - Steps to reproduce the behavior: Change of location in order to have a new weather location on watchface
 - Expected behavior: No overlapping between 2 locations (New is "Nivelles". Old is "Villers-la-Ville" 

![Image](https://github.com/user-attachments/assets/c8b900a1-0c86-4c02-9533-74f0d6d4126f)

 - Screenshots

**Comment by GreenBlack85** [comment]
done

**Comment by nicplet-netizen** [comment]
Unfortunately, after the last watchface version update of last night, the issue is still there... 🫤

![Image](https://github.com/user-attachments/assets/39e19565-d16f-4fbf-97e4-279e857db58d)

**Comment by GreenBlack85** [comment]
Did you restart your watch after the update? 
The old version keeps running after an update (annoying Garmin bug), usually a restart is needed, sometimes switching watchfaces back and forth works as well.

**Comment by nicplet-netizen** [comment]
Thank you for you (very) prompt answer! You are right, it's working as expected. Thanks a lot and congratulations for your great work.

**Comment by GreenBlack85** [comment]
Awesome! Thank you so much for your report! Very much appreciated

**Comment by nicplet-netizen** [comment]
![Image](https://github.com/user-attachments/assets/4f4bd080-340b-4354-bb47-03095b2afb1a)
Hi again, it seems that sometimes, the issue is back, but not always. It is easily solved by entering in the watchface selection menu but a little bit annoying. 
Not a big deal, but for you information if needed... 😉

**Comment by nicplet-netizen** [comment]
Just a kind reminder to reopen issue if you consider it's needed. I confirm that I have already restarted the watch several times after installing the update watchface. The issue is temporarily solved by entering in the watchface menu but need sometimes to be repeated. The issue does not always occur but only sometimes... Strange... 😉

**Comment by GreenBlack85** [comment]
Thanks for the reminder. I'm still working on a fix that hopefully will be pushed some time today. I'll reopen this

**Comment by GreenBlack85** [comment]
fixed
